name: CD Deploy to Azure Web App

on:
  workflow_dispatch: # Permite que o workflow seja acionado manualmente
  push:
    branches:
      - main # Opcional, caso queira disparar o CD automaticamente quando há push na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: dotnet-artifact # Nome do artefato gerado pelo workflow de CI

    - name: Extract artifact
      run: unzip my_dotnet_project.zip -d ./output

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: '<your-app-name>' # Substitua pelo nome do seu Web App no Azure
        slot-name: 'production' # Substitua pelo nome do slot, se aplicável
        publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
        package: ./output
